### ISSUE TITLE
`to_yaml` and `validate_spec` fails when using the `BasePlugin`

### ISSUE THREAD

**Issue by TheGrandmother** [marshmallow-code/apispec#234] opened 2018-07-04 12:47 UTC
I get a `AttributeError: 'Path' object has no attribute 'items'` when I try to use the `to_yaml` on a spec that uses a `BasePlugin` to handle path docstrings.

I am running apispec version 0.39.0 and python version 3.6.5

This is the little plugin that I'm using (from the docs):
```python
class DocPlugin(BasePlugin):

    def init_spec(self, spec):
        super(DocPlugin, self).init_spec(spec)
        self.openapi_major_version = spec.openapi_version.major

    def path_helper(self, path, func, **kwargs):
        operations = load_operations_from_docstring(func.__doc__)
        # Apply conditional processing
        if self.openapi_major_version < 3:
            pass
        else:
            pass
        return Path(path=path, operations=operations)
```

The path handler function looks like this:
```python
    async def get_task(self, request, name):
        '''test.
        ---
        get:
            responses:
                200:
                    schema: 'TaskSchema'
        '''
        try:
            result = await self.repository.get_task_by_name(name)
            return response.json(result)
        except TaskNotFound as err:
            return response.json(err.message, status=404)
```

And this is the part where I generate the the spec:
```python
        self.spec = APISpec(
            title='Matomatic Sandbox',
            version='1.0.0',
            openapi_version='3.0',
            plugins=[
                    DocPlugin(),
                    'apispec.ext.marshmallow'
            ])

        self.spec.definition('Task', schema=TaskSchema)
        self.spec.add_path('/task/{name}', func=self.get_task)
        print(self.spec.to_yaml())
        self.spec.validate_spec()
```

It fails with the following full stacktrace when the `to_yaml` is present:
```
Traceback (most recent call last):
  File "app.py", line 133, in <module>
    App().get_app().run('127.0.0.1', 9090, debug=True)
  File "app.py", line 105, in __init__
    print(self.spec.to_yaml())
  File "/usr/local/lib/python3.6/dist-packages/apispec/core.py", line 196, in to_yaml
    return yaml.dump(self.to_dict(), Dumper=YAMLDumper)
  File "/home/grandmother/.local/lib/python3.6/site-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/grandmother/.local/lib/python3.6/site-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/home/grandmother/.local/lib/python3.6/site-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "/home/grandmother/.local/lib/python3.6/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/grandmother/.local/lib/python3.6/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/grandmother/.local/lib/python3.6/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/grandmother/.local/lib/python3.6/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/local/lib/python3.6/dist-packages/apispec/core.py", line 453, in _represent_dict
    return dumper.represent_mapping('tag:yaml.org,2002:map', instance.items())
  File "/home/grandmother/.local/lib/python3.6/site-packages/yaml/representer.py", line 115, in represent_mapping
    node_key = self.represent_data(item_key)
  File "/home/grandmother/.local/lib/python3.6/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/local/lib/python3.6/dist-packages/apispec/core.py", line 453, in _represent_dict
    return dumper.represent_mapping('tag:yaml.org,2002:map', instance.items())
AttributeError: 'Path' object has no attribute 'items'
```

If the `to_yaml` line is commented out it fails with this stack trace:
```
Traceback (most recent call last):
  File "app.py", line 133, in <module>
    App().get_app().run('127.0.0.1', 9090, debug=True)
  File "app.py", line 106, in __init__
    validate_spec(self.spec)
  File "/usr/local/lib/python3.6/dist-packages/apispec/utils.py", line 114, in validate_spec
    prance.BaseParser(spec_string=json.dumps(spec.to_dict()), **parser_kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
```

If i remove the `DocPlugin()` from the plugin list it all works.

**Comment by lafrech** [comment] 2018-07-04 13:31
Thanks for reporting.

This is unrelated to `BasePlugin`. I can reproduce with this simple code:

```python
from apispec import APISpec, Path
from apispec.utils import load_operations_from_docstring


def path_helper(spec, path, func, **kwargs):
    operations = load_operations_from_docstring(func.__doc__)
    return Path(path=path, operations=operations)

def get_task(self, request, name):
        '''test.
        ---
        get:
            responses:
                200:
                    schema: 'TaskSchema'
        '''
        pass

spec = APISpec(
    title='Matomatic Sandbox',
    version='1.0.0',
    openapi_version='3.0',
)

spec.register_path_helper(path_helper)

spec.add_path('/task/{name}', func=get_task)
print(spec.to_dict())
print(spec.to_yaml())
```

`git bisect` pointed the culprit, which is a commit of mine...

Since https://github.com/marshmallow-code/apispec/pull/190 was merged (released as 0.34.0), `Path` does not inherit from `dict` anymore, hence the error.

AFAIU, this should be fixed by modifying `core.py`:

```python
class YAMLDumper(yaml.Dumper):

    @staticmethod
    def _represent_path(dumper, instance):
        return dumper.represent_mapping('tag:yaml.org,2002:map', instance.operations.items())

    @staticmethod
    def _represent_dict(dumper, instance):
        return dumper.represent_mapping('tag:yaml.org,2002:map', instance.items())

    if PY2:
        @staticmethod
        def _represent_unicode(_, uni):
            return yaml.ScalarNode(tag=u'tag:yaml.org,2002:str', value=uni)


if PY2:
    yaml.add_representer(unicode, YAMLDumper._represent_unicode, Dumper=YAMLDumper)
yaml.add_representer(OrderedDict, YAMLDumper._represent_dict, Dumper=YAMLDumper)
yaml.add_representer(LazyDict, YAMLDumper._represent_dict, Dumper=YAMLDumper)
yaml.add_representer(Path, YAMLDumper._represent_path, Dumper=YAMLDumper)
```

When testing this, I get a few glitches:

```yaml
components:
  parameters: {}
  schemas: {}
info: {title: Matomatic Sandbox, version: 1.0.0}
openapi: '3.0'
paths:
  ? get: &id001
      responses:
        200: {schema: TaskSchema}
  : get: *id001
tags: []
```

I don't use yaml and this feature is unknown territory to me so I can't really conclude.

Maybe anyone will know better.

**Comment by lafrech** [comment] 2018-07-05 13:26
OK, I got a better understanding now. The fix above is wrong. There should be no `Path` in the spec `dict` at this stage.

The path helper should be modified like this to let the code succeed:

```python
    def path_helper(self, path, func, **kwargs):
        operations = load_operations_from_docstring(func.__doc__)
        # Apply conditional processing
        if self.openapi_major_version < 3:
            pass
        else:
            pass
        return Path(path=path.path, operations=operations)  # s/path/path.path/
```

The problem is that when instantiating a `Path` with a `Path` instance as `path` parameter, it just stores is as a `Path` instance.

This could be fixed with a simple change do `Path`:

```python
 class Path(object):
     def __init__(self, path=None, operations=None, openapi_version='2.0'):
-        self.path = path
+        self.path = path is not isinstance(path, Path) else path.path
```

Or we could change `add_path` instead:

```python
         # Execute path helpers
         for plugin in self.plugins:
             try:
-                ret = plugin.path_helper(path=path, operations=path.operations, **kwargs)
+                ret = plugin.path_helper(path=path.path, operations=path.operations, **kwargs)
```

I think the logic in `core.py` is pretty complicated because every object/function can receive path as either a `str` or a `Path`. The code in `add_path` juggles with `Path` and `str` instances.

It think it kinda smells to pass both a `Path` instance and its `operations` attribute to the helpers. Either we pass both the path as a string and the operations as a dict, either we pass just the `Path` instance.

I'm pretty sure most cases are unused in practice (judging from builtin plugins and from mine). Besides, most of the time, when a `Path` is passed, only its `path` attribute is used, as its `operations` attribute is ignored since the `operations` parameter is used instead, so there may already be hidden issues.

This should be simplifiable in a not-so-breaking way.

Meanwhile, we may fix the doc to use `path.path` in the helper.

@sloria, any opinion about this?

**Comment by TheGrandmother** [comment] 2018-07-05 13:32
Changing it to: 
```python
 return Path(path=path.path, operations=operations)
```
Fixes it for me!
Thanks <3

**Comment by lafrech** [comment] 2018-07-06 19:57
I tried to address issues in https://github.com/marshmallow-code/apispec/issues/234#issuecomment-402721071 in those refactor PRs:

- https://github.com/marshmallow-code/apispec/pull/237
- https://github.com/marshmallow-code/apispec/pull/238

**Closed as completed** 2018-07-15 21:17 UTC
