### ISSUE TITLE
marshmallow plugin does not support `marshmallow.fields.Tuple`

### ISSUE THREAD

**Issue by saabeilin** [marshmallow-code/apispec#817] opened 2023-01-11 21:43 UTC
Unfortunately there's not support for `marshmallow.fields.Tuple`, instead such fields become "any" in the schema. Is there any plan to implement it?

**Comment by lafrech** [comment] 2023-01-12 08:04
Dupe of #399.

**Closed as completed by lafrech** 2023-01-12 08:04 UTC
