### ISSUE TITLE
Recursive dependency causes RecursionError

### ISSUE THREAD

**Issue by KPilnacek** [marshmallow-code/apispec#212] opened 2018-05-16 07:03 UTC
Hello,

at first thanks for this package 👍. I saves me a lot of effort with docs 🙂 .

I have a schema as follows
```python
from marshmallow import Schema, fields

class OneDataPointSchema(Schema):
    content = fields.Nested('self',
                            many=True,
                            exclude=('content', ),
                            )
```
 and everything works as expected, however, my data have tree structure with possibly infinite recursive depth (in reality about 2 - 3 levels are more than enough). Thus, I need to remove the `exclude` parameter. In that moment, the docs fails to render due to `RecursionError` (I was fine with that as the documentation is not that necessary). However, after upgrading to 0.37.0 (particularly in 3b6a2da6d13b8252217c7f60d49c38a29965359c) the `RecursionError` appears even before the documentation is generated (our code is than broken 🙁).

Is there a way to limit the recursion depth (by configuring `apispec` in particular)? I understand that rendering infinite recursion is impractical.

Thanks for advices
Krystof

P.S. FYI I'm tomorrow leaving for vacation for 3 weeks, thus please apologise my inactivity in that period.

**Comment by lafrech** [comment] 2018-05-16 07:54
Can't look at it right now but it should be feasible to avoid the `RecursionError` without defining a limit.

**Comment by KPilnacek** [comment] 2018-05-16 10:59
Thanks for looking into that eventually. No hurry, I just used the old version 🙂

**Comment by Chris2048** [comment] 2018-06-21 13:59
Is this ticket already covered by the aim of https://github.com/marshmallow-code/apispec/issues/212 ?

**Comment by lafrech** [comment] 2018-06-21 14:04
@Chris2048, I tried to follow your link and got a... `RecursionError`.

**Comment by Chris2048** [comment] 2018-06-21 14:40
Whoops :-D

Should be https://github.com/marshmallow-code/apispec/issues/55

**Comment by lafrech** [comment] 2018-07-16 13:14
Sorry @KPilnacek, I didn't have the time to look into this. AFAIU, the only clean way around this is to use a definition so that the schema can be replaced by its reference. This is not an apispec limitation.

Do you define a reference to `OneDataPointSchema` in your code?

I didn't understand everything about the fix @Chris2048 points to but it looks like it was meant to solve your use case.

If you're still stuck, you may want to show a reproducible example with a traceback. Ideally on a recent revision/release.

**Comment by KPilnacek** [comment] 2018-07-16 15:22
@lafrech no problem, thanks for responding anyway 🙂 . Honestly, I'm lost in these reference thinks. I tried to replace the `'self'` with `'OneDatapoitSchema'` as I understood from the [other issue](https://github.com/marshmallow-code/apispec/issues/55#issuecomment-203644221), however, it did not help. The rest, which was posted by @Chris2048 , I didn't get. So I'm still stucked 🙁 .

Anyway, the minimal "working" example is:
```python
from flask import Flask
from flask_apispec import FlaskApiSpec, use_kwargs
from flask_apispec.views import MethodResourceMeta
from flask_restful import Api, Resource
from marshmallow import fields, Schema

app = Flask(__name__)

api = Api(app)

docs = FlaskApiSpec(app)


class OneDataPointSchema(Schema):
    content = fields.Nested('OneDataPointSchema', many=True)


class Validate(Resource, metaclass=MethodResourceMeta):
    @use_kwargs(OneDataPointSchema())
    def post(self, content: dict):
        return content


api.add_resource(Validate, '/validate')
docs.register(Validate)

if __name__ == '__main__':
    app.run()
```

and the stacktrace:
```
Traceback (most recent call last):
  File "/Users/KPilnacek/workspace/elis_connector/mwe.py", line 26, in <module>
    docs.register(Validate)
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/flask_apispec/extension.py", line 119, in register
    resource_class_args, resource_class_kwargs)
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/flask_apispec/extension.py", line 66, in _defer 
    bound()
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/flask_apispec/extension.py", line 146, in _register
    self.spec.add_path(**path)
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/core.py", line 228, in add_path
    func(self, path=path, operations=operations, **kwargs)
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py", line 188, in schema_operation_resolver
    operation['parameters'] = resolve_parameters(spec, operation['parameters'])
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py", line 204, in resolve_parameters
    resolve_schema(spec, parameter)
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py", line 229, in resolve_schema
    data['schema'] = resolve_schema_dict(spec, data['schema'])
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py", line 241, in resolve_schema_dict
    for k, v in schema['properties'].items()}
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py", line 241, in <dictcomp>

...

  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py", line 241, in <dictcomp>
    for k, v in schema['properties'].items()}
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py", line 238, in resolve_schema_dict
    schema['items'] = resolve_schema_dict(spec, schema['items'], use_instances=use_instances)
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py", line 241, in resolve_schema_dict
    for k, v in schema['properties'].items()}
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/lazy_dict.py", line 20, in items
    return [(key, self.__getitem__(key)) for key in self.keys()]
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/lazy_dict.py", line 20, in <listcomp>
    return [(key, self.__getitem__(key)) for key in self.keys()]
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/lazy_dict.py", line 34, in __getitem__
    self[key] = item = item()
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/ext/marshmallow/swagger.py", line 612, in <lambda>
    field_obj, spec=spec, use_refs=use_refs, dump=dump, name=name)
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/apispec/ext/marshmallow/swagger.py", line 378, in field2property
    ret.update(schema2jsonschema(field.schema, dump=dump))
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/marshmallow/fields.py", line 427, in schema 
    dump_only=self._nested_normalized_option('dump_only'))
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/marshmallow/schema.py", line 335, in __init__
    self.declared_fields = copy.deepcopy(self._declared_fields)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/Users/KPilnacek/workspace/venv/lib/python3.6/site-packages/marshmallow/base.py", line 28, in __deepcopy__
    ret = copy.copy(self)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 106, in copy
    return _reconstruct(x, None, *rv)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 274, in _reconstruct
```

On `apispec=<0.36.0` this at least starts, however, the documentation does not work anyway.

**Comment by lafrech** [comment] 2018-09-21 13:42
@KPilnacek do you think you could provide a minimal example not depending on external libs (flask-apispec, flask-restful)?

**Comment by lafrech** [comment] 2018-09-21 13:51
This works (using latest revision in `dev` branch).

```py
from flask import Flask
from apispec import APISpec
from apispec.ext.marshmallow import MarshmallowPlugin
from marshmallow import fields, Schema

app = Flask(__name__)

spec = APISpec('Test', '0', '2.0', plugins=(MarshmallowPlugin(), ))


class OneDataPointSchema(Schema):
    content1 = fields.Nested('OneDataPointSchema', many=True)
    content2 = fields.Nested('self', many=True)


spec.definition('OneDataPointSchema', schema=OneDataPointSchema)

print(spec.to_dict())
```

Closing as "can't reproduce".

Please reopen if you can produce a failing test.

**Closed as completed by lafrech** 2018-09-21 13:51 UTC
