### ISSUE TITLE
Should marshmallow helpers respect `only`, `exclude`?

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/apispec#35] opened 2015-10-24 05:09 UTC
When introspecting `Nested` fields, we don't check for the `only` or `exclude` attributes. For example:

``` python
class FooSchema(Schema):
    bar = fields.Str()
    baz = fields.Str()

class BobSchema(Schema):
    foo = fields.Nested(FooSchema, only=('bar', ))
```

If we call `schema2jsonschema(BobSchema)`, the nested `foo` will include `bar` and `baz` fields, even though `baz` will never be included in this case. Which isn't necessarily a problem, unless `baz` is required:

``` python
class FooSchema(Schema):
    bar = fields.Str()
    baz = fields.Str(required=True)
```

In this case, users of apispec will likely return JSON that wouldn't validate against the definition schema, since there's going to be a missing required field. I haven't actually encountered this situation, and I don't know how often it's going to come up--just wanted to raise for discussion.

**Comment by jta** [comment] 2015-11-10 13:57
I was bitten by this recently. I foolishly assumed that the helpers would respect `exclude` as I use it to break cycles, but in hindsight I'm not sure it should. From the perspective of Swagger, removing a field changes the model. I suspect the only sane way of resolving your example would be:

```
class FooBaseSchema(Schema):
    bar = fields.Str()

class FooBaseSchema(FooSchema):
    baz = fields.Str()

class BobSchema(Schema):
    foo = fields.Nested(FooBaseSchema)
```

**Comment by whoiswes** [comment] 2016-04-06 15:14
+1 for fixing/working-around this in a sane and compatible way.

**Comment by martinlatrille** [comment] 2016-10-10 13:36
+1

For now I'm using `meta` to store only/exclude, and use them in a doc-generating project to shorten the `example outputs` of my endpoints.

```
"user": {
  "$ref": "#/definitions/User",
  "meta": {
    "only": [
      "id",
      "email",
      "name"
    ]
  }
}
```

A first fix could be to include those in the `meta` by default, to just make it available for client-side usage (without needing a duplicate declaration in the field's declaration).

```
user = fields.Nested(UserSchema, only=['id', 'email', 'name'], meta={
  'only': ['id', 'email', 'name']
})
```

As said by jmcarp, the OpenAPI spec doesn't allow such things at this time, so for now the only solutions are at least not supported, at most incompatible with the spec. Though, they're still required by most.

This approach (using `meta`) wouldn't break compatibility with other doc-reader, just allow us client developers to use the data.

If you guys accept it, I can do a PR 👍

**Comment by sloria** [comment] 2016-10-23 15:50
Thanks for posting your workaround @martinlatrille . I am hesitant to add code that adds arbitrary data to `meta`, especially when it's not part of the spec.

**Comment by ghost** [comment] 2017-11-28 13:03
When the "model" is altered with only/exclude, shouldn't it be considered as another "model"?
And so, having an inline definition respecting the only/exclude? (like if the schema was not registered)

**Comment by raphaeldehoussefaktory** [comment] 2017-11-28 16:48
In function `resolve_schema_dict`, line 175, if I add `use_refs=False` to function call `schema2jsonschema` and I use a `schema_definition_helper` to set `use_refs=False` to function call `schema2jsonschema` then I don't have the issue.
The problem is that it can't be done without changing the line 175 of __init__ of marshmallow extension :/

**Comment by lafrech** [comment] 2018-10-06 21:26
More or less related to https://github.com/marshmallow-code/apispec/issues/169 because it deals with schema modifiers.

Bottom line: for now, stay away from modifiers.

We could add a warning about those into the docs. Suggestions welcome.

**Closed as completed** 2019-01-25 14:12 UTC
