### ISSUE TITLE
Paths with defaults do not get recognized

### ISSUE THREAD

**Issue by ukaratay** [marshmallow-code/apispec#171] opened 2017-11-30 23:37 UTC
I have multiple paths in my Flask app:

```python
app.add_url_rule('/v1/models', defaults={'id': None}, view_func=analytics_model_v1, methods=['GET'])
app.add_url_rule('/v1/models', view_func=analytics_model_v1, methods=['POST'])
app.add_url_rule('/v1/models/<string:id>', view_func=analytics_model_v1, methods=['DELETE', 'GET', 'PATCH', 'PUT'])
```
When I add this view function to APISpec, it does not recognize the path /v1/models/<string:id>:

```python
with app.test_request_context():
    spec.add_path(view=analytics_model_v1)
```

```python
>>> pprint(spec.__path)
OrderedDict([('/models',
              {'delete': {'description': '',
                          'operationId': 'deleteModel',
                          'parameters': ...,
                          'produces': ...,
                          'responses': ...,
                          'summary': 'Delete an existing model',
                          'tags': ['model']},
               'get': {'consumes': ['application/json'],
                       'description': '',
                       'operationId': 'getModel',
                       'parameters': ...,
                       'produces': ['application/json'],
                       'responses': ...,
                       'summary': 'Get an existing model',
                       'tags': ['model']},
               'patch': {'consumes': ['application/json'],
                         'description': '',
                         'operationId': 'updateModel',
                         'parameters': ...,
                         'produces': ['application/json'],
                         'responses': ...,
                         'summary': 'Update an existing model',
                         'tags': ['model']},
               'post': {'consumes': ['application/json'],
                        'description': '',
                        'operationId': 'buildModel',
                        'parameters': ...,
                        'produces': ['application/json'],
                        'responses': ...,
                        'summary': 'Build a new model',
                        'tags': ['model']},
               'put': {'consumes': ['application/json'],
                       'description': '',
                       'operationId': 'rebuildModel',
                       'parameters': ...,
                       'produces': ['application/json'],
                       'responses': ...,
                       'summary': 'Rebuild an existing model with new '
                                  'parameters',
                       'tags': ['model']}})])
```
I looked through documentation and the code, but couldn't see any examples like this or an option.

P.S. I had to redact some information from the output. Denoted by ellipsis.

**Comment by lafrech** [comment] 2018-04-04 13:47
I think this is due to the "one rule per view function" limitation.

See https://github.com/marshmallow-code/apispec/issues/181.

Closing this as duplicate of #181. Feel free to reopen if I'm wrong about this.

**Closed as completed by lafrech** 2018-04-04 13:47 UTC
