### ISSUE TITLE
Incorrectly serialized format when using a range validator on a Decimal Marshmallow field

### ISSUE THREAD

**Issue by intZero** [marshmallow-code/apispec#869] opened 2023-11-29 14:01 UTC
Hello! One of our Marshmallow serializers includes this field:
`conversion_factor = fields.Decimal(required=True, validate=[Range(min=0)])`

In 6.1.0+ this serializes to:
```
conversion_factor:
  type: number
  minimum: !!python/object/apply:decimal.Decimal
  - '0'
```
I've traced the issue to this section of code in field2range() in field_converter.py:
```
# Serialize min/max values with the field to which the validator is applied
return {
    k: field._serialize(v, None, None)
    for k, v in make_min_max_attributes(validators, min_attr, max_attr).items()
}
```
The main problem is that in _serialize for a Number:
```
"""Return a string if `self.as_string=True`, otherwise return this field's `num_type`."""
```
And since for a Decimal field the default self.as_string=False (standard usage) we get "!!python/object/apply:decimal.Decimal". I suggest that for field types where _serialize does this you instead run _to_string which will format the number accordingly:
```
conversion_factor:
  type: number
  minimum: '0.000000'
```

**Comment by lafrech** [comment] 2023-11-30 13:08
Thanks for reporting. Would you like to work on this (change + test)?

**Comment by intZero** [comment] 2023-12-01 11:04
Yeah I've made the change and written a couple of tests for it, should I open a PR against dev?

**Comment by lafrech** [comment] 2023-12-01 11:06
Yes, please !

**Comment by intZero** [comment] 2023-12-01 11:21
Cool, could I get access to create branch intzero/fix-decimal-range please?

**Comment by lafrech** [comment] 2023-12-01 11:37
The procedure is to push the branch to your GH fork, then open the PR.

**Comment by intZero** [comment] 2023-12-01 11:57
My bad! Have opened a PR here https://github.com/marshmallow-code/apispec/pull/870

**Comment by lafrech** [comment] 2023-12-04 08:39
Sorry for not spotting this any sooner, but I think the way to go is to set `as_string=True` in `Decimal` field, rather than adding field-specific code in a generic function.

See 

- https://github.com/marshmallow-code/flask-smorest/issues/517
- https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Decimal

**Comment by intZero** [comment] 2023-12-04 09:50
Yeah I saw your reply to the PR. I really don't think that asking people to change their business logic by changing the serializer to use a different variable type is a solution imho! Secondly, it isn't a solution anyway as you will end up with:
```  
type: number
  minimum: '0'
  maximum: '1000000'
```
This range is processed by OpenAPI as a string and thus doesn't correctly display the range for this field since it is a number. The other problem you're going to have is when outputting yaml with Decimals. Seeing as pyyaml (the library that your to_yaml() function uses and seems to be the only viable yaml library for python) doesn't support them (which is why this issue is similar to the one you linked with the json library). There are a number of issues like this https://github.com/yaml/pyyaml/issues/255 which have been open for years with no reply or merge so it doesn't look like it'll get fixed anytime soon either. Sometimes to fix a problem you need to make pragmatic concessions.

No problem - it's starting to look as though the solution is me writing a work-around in my doc build tools to specifically deal with Decimals. I can close my PR.

**Comment by lafrech** [comment] 2023-12-04 10:07
Le 2023-12-04 10:50, Nick Anderton a écrit :
> Yeah I saw your reply to the PR. I really don't think that asking
> people to change their business logic by changing the serializer to
> use a different variable type is a solution imho!

Well, I wouldn't call that changing business logic. We're talking about 
the way marshmallow serializes data.

Now I'm wondering. If your API works, then I guess you're not using 
standard json serializer. Why not use that serializer for the API docs? 
There must be something I don't understand in your use case. My point is 
that min/max are serialized the same way as API return values, so there 
shouldn't be anything specific about the docs.

> Secondly, it isn't a
> solution anyway as you will end up with:
> ```
> type: number
>   minimum: '0'
>   maximum: '1000000'
> ```
> This range is processed by OpenAPI as a string and thus doesn't
> correctly display the range for this field since it is a number.

Good point.

I guess the problem is that by definition decimals are not meant to be 
written as numbers.

Perhaps string is fine after all.

(Looks like PayPal does that: 
https://stackoverflow.com/questions/35709595/why-would-you-use-a-string-in-json-to-represent-a-decimal-number)

> The other problem you're going to have is when outputting yaml with
> Decimals. Seeing as pyyaml (the library that your to_yaml() function
> uses and seems to be the only viable yaml library for python) doesn't
> support them (which is why this issue is similar to the one you linked
> with the json library). There are a number of issues like this
> https://github.com/yaml/pyyaml/issues/255 which have been open for
> years with no reply or merge so it doesn't look like it'll get fixed
> anytime soon either. Sometimes to fix a problem you need to make
> pragmatic concessions.

OK so IIUC, pyyaml has the same limitation as standard json. Isn't this 
another reason to treat the problem at field level and serialize as 
string?

> No problem - it's starting to look to me as though the solution is me
> writing a work-around in my build tools to specifically deal with
> Decimals.

Ultimately, yes. But I'd be happy if we could figure out an acceptable 
solution here.

-- 
Jérôme

**Comment by lafrech** [comment] 2024-02-26 21:04
> Now I'm wondering. If your API works, then I guess you're not using
standard json serializer. 

The reason is that I didn't know that Flask JSON encoder had been improved to serialize decimals as well, so no need for a custom decimal serializer anymore.

My other points still stand. Users should use `as_string` with `Decimal` fields.

Closing for now. Feel free to comment for further discussion.

**Closed as completed by lafrech** 2024-02-26 21:04 UTC
